# Build and release new version of the resume if new tag is added.
name: "gh-pages"

on:
  #push:
    #branches:
    #  - "main"
    #tags:
    #  - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-resume:
    runs-on: "ubuntu-20.04"
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: "actions/checkout@v2"

      - name: "Install dependencies"
        run: "sudo apt install pandoc context"

      - name: "Build resume"
        run: |
          source ./source.sh
          pdf
          html
          rm ./public/*.log ./public/*.tex ./public/*.tuc
          mv ./public/resume.html ./public/index.html

      - name: "Deploy to GitHub pages"
        uses: "peaceiris/actions-gh-pages@v3"
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          publish_dir: "./public"
