# Build and release new version of the resume if new tag is added.
name: "netlify"

on:
  push:
    #branches:
    #  - "main"
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-resume:
    runs-on: "ubuntu-20.04"
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: "actions/checkout@v2"
        with:
          # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          persist-credentials: false
          # otherwise, there would be errors pushing refs to the destination repository.
          fetch-depth: 0

      - name: "Install dependencies"
        run: |
          sudo apt install git pandoc context

      - name: "Build resume"
        run: |
          source ./source.sh
          pdf
          html
          rm ./public/*.log ./public/*.tex ./public/*.tuc
          mv ./public/resume.html ./public/index.html
          ls --almost-all --recursive --ignore=.git

      - name: "Create and push new orphan branch"
        run: |
          git config --local user.name "jaantollander"
          git config --local user.email "jaantollander@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git checkout --orphan "netlify"
          git rm --cached "netlify.toml"
          git rm -rf .
          git add .
          git commit -m "gh-actions"
          git push origin "netlify" -f
          ls --almost-all --recursive --ignore=.git
